export var commit = {
  sha: '',
  node_id: '',
  commit: {
    author: {
      name: '',
      email: '',
      date: '',
    },
    committer: {
      name: '',
      email: '',
      date: '',
    },
    message: '',
    tree: {
      sha: '',
      url: '',
    },
    url: '',
    comment_count: '',
    verification: {
      verified: '',
      reason: '',
      signature: '',
      payload: '',
    },
  },
  url: '',
  html_url: '',
  comments_url: '',
  author: {
    login: '',
    id: '',
    node_id: '',
    avatar_url: '',
    gravatar_id: '',
    url: '',
    html_url: '',
    followers_url: '',
    following_url: '',
    gists_url: '',
    starred_url: '',
    subscriptions_url: '',
    organizations_url: '',
    repos_url: '',
    events_url: '}',
    received_events_url: '',
    type: '',
    site_admin: '',
  },
  committer: {
    login: '',
    id: '',
    node_id: '',
    avatar_url: '',
    gravatar_id: '',
    url: '',
    html_url: '',
    followers_url: '',
    following_url: '',
    gists_url: '',
    starred_url: '',
    subscriptions_url: '',
    organizations_url: '',
    repos_url: '',
    events_url: '',
    received_events_url: '',
    type: '',
    site_admin: '',
  },
  parents: [
    {
      sha: '',
      url: '',
      html_url: '',
    },
  ],
};
